import type { Metadata } from "next";
import {
  Inter,
  Reddit_Mono,
  Plus_Jakarta_Sans,
  JetBrains_Mono,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ThemeToggle from "@/components/ThemeToggle";
import Header from "@/components/Header";
import { JsonDataProvider } from "@/context/JsonDataContext";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });
const reddit = Reddit_Mono({ subsets: ["latin"] });
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });
const jetBrains = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetBrains.className}>
        <JsonDataProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-[100dvh] flex flex-col">
              <Header />
              <div className="flex flex-col flex-grow overflow-hidden">
                {children}
              </div>
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </JsonDataProvider>
      </body>
    </html>
  );
}
